.TH UNMAP "1" "Feb 2008" "joymap 0.0.1" "User Commands"
.SH NAME
unmap \- remove all joystick mappings
.SH SYNOPSIS
.B unmap
.SH DESCRIPTION
.\" Add any additional description here
.PP
Remove all joystick mappings. No joysticks will be available
in the system, other than those physically plugged in.
.PP
Exit status is always 0, even after failure.
.SH "SEE ALSO"
loadmap (1) 
.SH AUTHOR
Written by Alexandre Hardy.
.SH "REPORTING BUGS"
Report bugs to <alexandre.hardy@gmail.com>.
.SH "LICENSE"
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
